---
# ansible-playbook frappe.yaml -i inventory --extra-vars "ansible_sudo_pass=asd dbname=erp2 site=erp.tarqim.info"
- hosts: nodes
  become: yes     
  tasks:
    - name: Create new site
      shell: |
        cd ./frappe-bench-demo
        bench new-site "{{ site }}" --db-name "{{ dbname }}" --mariadb-root-username root --mariadb-root-password asd --admin-password asd --verbose --force
        touch ./sites/currentsite.txt
        echo "{{ site }}" > ./sites/currentsite.txt        
        bench --site "{{ site }}" install-app erpnext
        bench --site "{{ site }}" install-app payments
        bench --site "{{ site }}" install-app healthcare
        bench --site "{{ site }}" install-app hrms

        
