---
# ansible-playbook frappe.yaml -i inventory --extra-vars "ansible_sudo_pass=asd"
- hosts: master
  become: yes     
  tasks:
    - name: Create new site
      shell: |
        cd ./frappe-bench-demo
        bench new-site demo2.tarqim.info --db-name demo2_erp --mariadb-root-username root --mariadb-root-password asd --admin-password asd --verbose --force
        touch ./sites/currentsite.txt
        echo "demo2.tarqim.info" > ./sites/currentsite.txt        
        bench --site demo2.tarqim.info install-app erpnext
        bench --site demo2.tarqim.info install-app payments
        bench --site demo2.tarqim.info install-app healthcare
        bench --site demo2.tarqim.info install-app hrms

        
